export const corePackageName = "@bomboard/core";

export type {
  BoardArtworkIR,
  BoardArtworkCircleIR,
  BoardArtworkLayerIR,
  BoardArtworkPaintIR,
  BoardArtworkPathIR,
  BoardArtworkPolygonIR,
  BoardArtworkPolylineIR,
  BoardArtworkPrimitiveBaseIR,
  BoardArtworkPrimitiveIR,
  BoardArtworkRectIR,
  BoardArtworkStyleIR,
  BoardGeometrySource,
  BoardSide,
  BomBoardProjectIR,
  BomIR,
  BomItemIR,
  BomSkipIR,
  BoardIR,
  BoardLayerFunction,
  BoardLayerIR,
  Bounds,
  CanonicalCoordinateSystem,
  ComponentIR,
  ComponentPlacementIR,
  DiagnosticSeverity,
  DrillHitIR,
  ImportDiagnostic,
  PadIR,
  Point,
  ProjectMetadata,
  SourceFileRecord,
  SourceFileRole,
  SourceRef,
  ViaIR,
  ViewBox,
} from "./ir.js";
export {
  BomBoardImportError,
  isBomBoardImportError,
} from "./runtime.js";
export type {
  BoardRenderModel,
  BoardRenderOptions,
  BoardProjectViewerMountOptions,
  BoardRenderBomSource,
  BoardRenderComponent,
  BoardRenderComponentElement,
  BoardRenderComponentSize,
  BoardRenderComponentSource,
  BoardRenderPlacementSide,
  BoardRenderPlacementSource,
  BoardRenderPoint,
  BoardRenderPointMm,
  BoardRenderer,
  BoardViewerComponentRef,
  BoardViewerHandle,
  BoardViewerHost,
  BoardViewerMountOptions,
  BoardViewerSelectionChange,
  BoardViewerSide,
  BoardViewerState,
  BoardViewerStateSource,
  BomBoardImportErrorCode,
  BomBoardRuntime,
  OpenProjectInput,
  OpenProjectResult,
  ProjectImportFile,
  ProjectImportInput,
  ProjectParseOptions,
  ProjectParser,
  ProjectParserProbe,
} from "./runtime.js";
